# Generated by Django 6.0.3 on 2026-04-30 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentschedule',
            name='duration_months',
            field=models.IntegerField(default=12),
        ),
    ]
